name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

 # Step 1: Checkout the Code
      - name: Checkout code
        uses: actions/checkout@v4
      
 # Step 2: Set Up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

 # Step 3: Cache Maven Dependencies (to speed up builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

 # Step 4: Build the Application with Maven
      - name: Build with Maven
        run: mvn clean install

 # Step 5: Save Build Artifact
      - name: Save Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-tomcat-app
          path: target/*.jar

 
 # Step 6: Trigger Jenkins Pipeline
      - name: Trigger Jenkins Pipeline
        run: |
          curl -X POST "http://admin:${{ secrets.JENKINS_API_TOKEN }}@localhost:8080/job/my-cicd-pipeline/build?token=my-trigger-token"

